const $=id=>document.getElementById(id);let state=null,csrf='',tab='password',lastEvents=0,polling=false;
const format=(value,short=false)=>value?new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',...(short?{}:{second:'2-digit'}),hour12:false}):'—';
function toast(message,error=false){$('toast').textContent=message;$('toast').className='toast'+(error?' error':'');$('toast').hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').hidden=true,4500)}
async function action(name,data={}){try{const response=await fetch('/api/'+name,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'操作失败');if(name==='settings')toast('配置已保存到本机');await poll();return true}catch(error){toast(error.message,true);return false}}
function configData(){return {intervalHours:Number($('interval').value),holdSeconds:Number($('hold').value),targetId:$('target').value,mobile:$('mobile').value.trim(),username:$('username').value.trim(),password:$('password').value,selected_username:$('selected_username').value.trim()}}
async function save(){const ok=await action('settings',configData());if(ok){for(const id of ['mobile','username','password','selected_username'])$(id).value='';for(const id of ['interval','hold','target'])delete $(id).dataset.dirty}return ok}
function setTab(value){tab=value;$('tab-password').classList.toggle('selected',value==='password');$('tab-sms').classList.toggle('selected',value==='sms');$('tab-password').setAttribute('aria-selected',value==='password');$('tab-sms').setAttribute('aria-selected',value==='sms');$('password-panel').hidden=value!=='password';$('sms-panel').hidden=value!=='sms';$('verification').hidden=value==='password'&&!state?.pending}
function render(data){state=data;csrf=data.csrf;$('service-status').replaceChildren();const dot=document.createElement('i');$('service-status').append(dot,document.createTextNode('本地服务正常'));
  $('session-status').textContent=data.authenticationRequired?'会话已失效':(data.sessionAvailable?'会话已保存':'尚未登录');$('session-status').className=data.sessionAvailable?'good':'';$('session-detail').textContent=data.authenticationRequired?'请重新登录，完成可能需要的短信验证':(data.sessionAvailable?'连接前刷新；票据失效时尝试密码续登':'请使用短信或密码登录');
  const r=data.lastResult;$('last-status').textContent=r?(r.success?'已进入系统':'连接未完成'):'暂无连接';$('last-status').className=r?.success?'good':'';$('last-detail').textContent=r?format(r.finishedAt||r.startedAt):'点击「立即连接一次」开始';
  $('loop-status').textContent=data.loopEnabled?'运行中':'未启动';$('loop-status').className=data.loopEnabled?'good':'';$('loop-detail').textContent=data.loopEnabled?'每 '+data.intervalHours+' 小时连接一次':'周期连接已停止';$('next-run').textContent=data.loopEnabled?(data.busy?'执行中':format(data.nextRunAt,true)):'—';$('next-detail').textContent=data.loopEnabled?'等待中 · 下一轮自动执行':'启动周期运行后显示';$('schedule-tag').textContent=data.loopEnabled?'已开启':'已停止';$('schedule-tag').className='tag'+(data.loopEnabled?' green':'');
  $('loop').textContent=data.loopEnabled?'Ⅱ 停止周期连接':'▷ 开启周期连接';$('loop').className='button grow '+(data.loopEnabled?'danger':'primary');$('loop').disabled=!data.loopEnabled&&(data.busy||!data.sessionAvailable);
  if(!$('interval').dataset.dirty)$('interval').value=data.intervalHours;if(!$('hold').dataset.dirty)$('hold').value=data.holdSeconds;$('hold-label').textContent=data.holdSeconds+' 秒';
  const select=$('target');if(!select.dataset.dirty){select.replaceChildren();for(const m of data.machines){const option=document.createElement('option');option.value=m.machineId;option.textContent=m.machineName+(m.originCompanyCode==='ZTE'?'':'（暂不支持）');option.disabled=m.originCompanyCode!=='ZTE';select.append(option)}if(!select.options.length){const o=document.createElement('option');o.textContent='暂无设备，请登录后刷新';o.value='';select.append(o)}select.value=data.targetId||''}
  const machine=data.machines.find(m=>m.machineId===data.targetId);$('machine-name').textContent=machine?.machineName||'尚未选择云电脑';$('machine-type').textContent=machine?.originCompanyCode?machine.originCompanyCode+' 云电脑 · '+((machine.resourceType||'').match(/(\d+)C(\d+)G/)?(machine.resourceType.match(/(\d+)C(\d+)G/)[1]+' 核 / '+machine.resourceType.match(/(\d+)C(\d+)G/)[2]+' GB'):'已配置资源'):'登录后刷新设备信息';$('machine-id').textContent=machine?.machineId?'设备 · …'+machine.machineId.slice(-8):'—';$('machine-status').textContent=machine?.machineStatus==='available'?'可用 · 已保存':(machine?.machineStatus==='shutdown'?'已关机':'本地缓存');$('machine-status').className='tag'+(machine?.machineStatus==='available'?' green':'');
  $('mobile').placeholder=data.auth.mobileHint||'填写完整绑定手机号';$('username').placeholder=data.auth.usernameConfigured?'已配置 · 留空保留':'填写账号';$('password').placeholder=data.auth.passwordConfigured?'已保存 · 留空保留':'填写密码';$('account-hint').textContent=data.auth.mobileHint||'本机保存';
  $('code-label').textContent=data.pending?'设备验证短信验证码':'登录短信验证码';$('challenge-hint').textContent=data.pending?'设备验证短信已发送，请输入最新验证码。':'';$('verify').textContent=data.pending?'完成验证':'验证登录';setTab(tab);
  for(const id of ['refresh','connect','power-connect','password-login','sms-send','verify'])$(id).disabled=data.busy||data.loopEnabled||(['connect','power-connect','refresh'].includes(id)&&!data.sessionAvailable);
  for(const id of ['save-settings','save-account','target','interval','hold','mobile','username','password','selected_username'])$(id).disabled=data.busy||data.loopEnabled;
  $('connect').textContent=data.busy&&data.action==='connect'?'正在连接，等待清理完成…':'↗ 立即连接一次';$('job-status').textContent=data.busy?'执行中':'空闲';$('job-status').className='tag'+(data.busy?' amber':'');
  $('history').replaceChildren();if(!data.history.length){const e=document.createElement('p');e.className='empty';e.textContent='暂无连接记录';$('history').append(e)}for(const item of data.history){const row=document.createElement('div');row.className='history-row';const desc=document.createElement('div'),title=document.createElement('strong'),time=document.createElement('small');title.textContent=format(item.finishedAt||item.startedAt);time.textContent=item.success?'已确认 Windows 登录并完成断开清理':(item.errorHint||(item.errorCode?'业务码 '+item.errorCode:'请检查会话或连接状态'))+(item.errorType?'（'+item.errorType+'）':'');desc.append(title,time);const duration=document.createElement('span');duration.className='duration';duration.textContent=item.controlHoldSeconds?item.controlHoldSeconds+'s':'—';const tag=document.createElement('span');tag.className='tag '+(item.success?'green':'red');tag.textContent=item.success?'成功':(item.legacyMainOnly?'仅认证':(item.legacyDisplayOnly?'仅画面':'未完成'));row.append(desc,duration,tag);$('history').append(row)}
  if(data.events.at(-1)?.id!==lastEvents){$('logs').replaceChildren();for(const event of data.events){const row=document.createElement('div');row.className='log '+event.level;const time=document.createElement('time'),message=document.createElement('span');time.textContent=new Date(event.at).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});message.textContent=event.message;row.append(time,message);$('logs').append(row)}$('logs').scrollTop=$('logs').scrollHeight;lastEvents=data.events.at(-1)?.id||0}
}
async function poll(){if(polling)return;polling=true;try{const response=await fetch('/api/state',{cache:'no-store'});if(!response.ok)throw Error();render(await response.json())}catch{$('service-status').textContent='本地服务未连接'}finally{polling=false}}
$('save-settings').onclick=save;$('save-account').onclick=save;$('refresh').onclick=()=>action('devices');$('connect').onclick=async()=>{if(await save())await action('connect')};$('power-connect').onclick=async()=>{if(await save())await action('power-connect')};$('loop').onclick=async()=>{if(state.loopEnabled)await action('loop-stop');else if(await save())await action('loop-start')};$('password-login').onclick=async()=>{if(await save())await action('password')};$('sms-send').onclick=async()=>{if(await save())await action('sms-send')};$('verify').onclick=async()=>{if(await action(state.pending?'challenge':'sms-login',{code:$('code').value.trim()}))$('code').value=''};$('tab-password').onclick=()=>setTab('password');$('tab-sms').onclick=()=>setTab('sms');document.querySelectorAll('.nav-link').forEach(link=>link.onclick=()=>{document.querySelectorAll('.nav-link').forEach(l=>l.classList.remove('active'));link.classList.add('active')});
for(const id of ['interval','hold','target'])$(id).addEventListener('input',()=>$(id).dataset.dirty='1');
setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})},1000);poll();setInterval(poll,1500);
